#!/usr/bin/env bash
# Display a list of currently running processes
### show all processes for all users
### including background ones which may not have a TTY
### Display a user-oriented format
### Show process hierarchy
 
ps -auxf
