#!/usr/bin/env bash
# tests for holberton school file, and determines if it is empty

num=1

while [ $num -le 100 ]
do
	if [[ $((num % 3)) -eq 0 && $((num % 5)) -eq 0 ]]
	then
		echo "FizzBuzz"
	elif [[ $((num % 3)) -eq 0 ]]
	then
		echo "Fizz"
	elif [[  $((num % 5)) -eq 0 ]]
	then
		echo "Buzz"
	else
		echo "$num"
	fi
	((num++))
done	
