#!/usr/bin/env bash
# Write a Bash script that displays Holberton School 10 times.

hour=0
min=1
while [ $hour -le 12 ] 
do
	echo "Hour: $hour"
	min=1
	while [ $min -le 59 ]
	do
		echo "$min"
		((min++))
	done
	((hour++))
done
