#!/usr/bin/env bash
# secure copies file to remote server
# args: 
#	1: file to transfer
#	2: remote machine
#	3: username
#	4: identity file
if [ $# -ne 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
fi
