#!/usr/bin/env bash

IFS=$'\n'
set -f
x=$(cat /etc/hosts.new)

echo "8.8.8.8 facebook.com" > /tmp/hosts
for i in $x
do
	case $i in
	*"8.8.8.8 facebook.com"*)
		true
		;;
	*)
		echo "${i/127.0.0.1 localhost/127.0.0.2 localhost}" >> /tmp/hosts
		;;
	esac
done

cp /tmp/hosts /etc/hosts
rm /tmp/hosts
